# File: templates/npm-with-params.yml

parameters:
- name: name  # defaults for any parameters that aren't specified
  default: ''
- name: vmImage
  default: ''

jobs:
- job: ${{ parameters.name }}
  pool: 
   name: production
   vmImage: ${{ parameters.vmImage }}
  steps:
  - script: uname -a
  - script: pwd