# File: templates/npm-with-params.yml

parameters:
- name: name  # defaults for any parameters that aren't specified
  default: ''
- name: vmImage
  default: ''
- name: displayName
  default: ''

jobs:
- job: ${{ parameters.name }}
  displayname: ${{ parameters.displayName }}
  pool: 
   name: production
   vmImage: ${{ parameters.vmImage }}
  steps:
  - script: echo ${{ parameters.name }}
  - script: echo ${{ parameters.vmImage }}