# File: templates/npm-with-params.yml

parameters:
- name: name  # defaults for any parameters that aren't specified
  default: ''
- name: vmImage
  default: ''
- name: poolName
  default: 'production'

jobs:
- job: ${{ parameters.name }}
  pool: 
   name: ${{ parameters.poolName }}
   vmImage: ${{ parameters.vmImage }}
  steps:
  - script: echo ${{ parameters.name }}
  - script: echo ${{ parameters.vmImage }}