# File: templates/steps-with-params.yml
pool: 
  name: production
  vmImage: 'ubuntu-latest'
parameters:
- name: 'runExtendedTests'  # defaults for any parameters that aren't specified
  type: boolean
  default: false

steps:
- script: uname -a
- ${{ if eq(parameters.runExtendedTests, true) }}:
  - script: df -h --extended