trigger:
- master

parameters:
  - name: Environment
    type: string
    default: dev

  - name: experimentalTemplate
    displayName: 'Use experimental build process?'
    type: boolean
    default: true

jobs:
- job:  ${{ parameters.Environment }}
  timeoutInMinutes: 10
  pool:
    name: production
    demands: agent.os -equals Linux

  steps:
  - ${{ if eq(parameters.experimentalTemplate, true) }}:
    - template: uat-step.yml
  - ${{ if not(eq(parameters.experimentalTemplate, true)) }}:
    - template: prod-step.yml
  
  #- template: simple-param.yml
  #- template: uat-step.yml
  #- template: prod-step.yml
   