trigger: none

pool: 
  vmImage: 'ubuntu-latest'

parameters:
- name: Operating_Systems
  type: string
  default: ubuntu
  values:
  - ubuntu
  - Redhat
  - CentOS
  - Windows

- name: Environment
  type: string
  default: Dev
  values:
  - Dev
  - UAT
  - Testing
  - Prod

jobs:
- job:  ${{parameters.Environment}}
  timeoutInMinutes: 10
#  pool:
#    name: production
#    demands: agent.os -equals Linux

  steps:
  - ${{ if eq(parameters.Environment, UAT) }}:
    - script: echo ${{ parameters.Environment }}
  - ${{ if not(eq(parameters.experimentalTemplate, true)) }}:
    - template: prod-step.yml