
parameters:
- name: 'runExtendedTests'  # defaults for any parameters that aren't specified
  type: boolean
  default: false

steps:
- ${{ if eq(parameters.runExtendedTests, true) }}:
  - script: uptime