trigger:
- master

variables: 
  - name: Environment
    value: dev

jobs:
- job:  ${{ variables.Environment }}
  timeoutInMinutes: 10
  pool:
    name: production
    demands: agent.os -equals Linux

  steps:
  - template: sample-template-step.yml
  - template: sample-template-step.yml
  - template: sample-template-step.yml
   