# File: templates/steps-with-params.yml
pool: 
  name: production
  vmImage: 'ubuntu-latest'


variables: 
- name: my-bare-variable
  variable: 'value-of-my-bare-variable'
  
- group: my-variable-group

steps:
  - script: echo $(my-variable-group)