trigger:
- master

parameters:
  - name: Environment
    type: string

#variables: 
#  - name: Environment
#    value: dev

jobs:
- job:  test
  timeoutInMinutes: 10
  pool:
    name: production
    demands: agent.os -equals Linux

  steps:
  - template: dev-step.yml
  - template: uat-step.yml
  - template: prod-step.yml
   