trigger:
- master

parameters:
  - name: Environment
    type: string

jobs:
- job:  ${{ parameters.Environment }}
  timeoutInMinutes: 10
  pool:
    name: production
    demands: agent.os -equals Linux

  steps:
  - template: dev-step.yml
  - template: uat-step.yml
  - template: prod-step.yml
   