trigger:
- master

jobs:
- job: myJob
  timeoutInMinutes: 10
  pool:
    name: production
    demands: agent.os -equals Linux

  steps:
  - template: sample-template-step.yml
  - template: sample-template-step.yml
  - template: sample-template-step.yml
   