# File: azure-pipelines.yml

jobs:
- template: npm-with-params.yml  # Template reference
  parameters:
    name: Linux
    vmImage: 'ubuntu-latest'
    #poolName: 'production'

- template: npm-with-params.yml  # Template reference
  parameters:
    name: macOS
    vmImage: 'macOS-latest'
    #poolName: 'production'

- template: npm-with-params.yml  # Template reference
  parameters:
    name: Windows
    vmImage: 'windows-latest'
    #poolName: 'production'