# File: templates/steps-with-params.yml
pool: 
  name: production
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: templates
      type: github
      name: azure-devops 
jobs:
- template: win-linux.yml@templates  # Template reference