# File: templates/steps-with-params.yml
pool: 
  name: production
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: azure-devops
      type: github
      name: templates

jobs:
- template: win-linux.yml@templates  # Template reference