trigger: none
pool: 
  vmImage: 'ubuntu-latest'
#pool:
#  name: production
#  demands: agent.os -equals Linux
variables:
#- group: PROD
- name: env
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    value: a
  ${{ else }}:
    value: b

steps:
- script: | 
    echo '$(name)'
    echo '$(env)'