trigger: none

pool: 
  vmImage: 'ubuntu-latest'

parameters:
- name: Operating_Syatems
  type: string
  default: ubuntu
  values:
  - ubuntu
  - Redhat
  - CentOS
  - Windows

- name: Environments
  type: string
  default: Dev
  values:
  - Dev
  - UAT
  - Testing
  - Prod

variables: 
- name: myENV
  value: ${{ parameters.Environments}}

steps:
  - script: echo ${{variables.myENV}}
    #condition: eq(variables.myENV, UAT)


