trigger:
- master

#parameters:
#  - name: Environment
#    type: string

variables: 
  - template: dev-step.yml
    parameters:
      moduleName: ${{ parameters.version }}

jobs:
- job:  ${{ parameters.version }}
  timeoutInMinutes: 10
  pool:
    name: production
    demands: agent.os -equals Linux

  steps:
  - template: dev-step.yml
  - template: uat-step.yml
  - template: prod-step.yml
   