# File: templates/steps-with-params.yml
pool: 
  name: production
  vmImage: 'ubuntu-latest'

stages:
- stage: Delete_Unused_Docker_images
  displayName: Delete Unused Docker images
  jobs:
  - job: 
    steps:
    - script: id ; docker image prune -a --force
