trigger: none

pool: 
  vmImage: 'ubuntu-latest'

parameters:
- name: myString
  type: string
  default: a string
- name: myMultiString
  type: string
  default: default
  values:
  - default
  - ubuntu
  - CentOS
  - Windows


- name: myStep
  type: step
  default:
    script: echo my step

jobs: 
- job: stepList
  steps: ${{ parameters.mySteplist }}
- job: myStep
  steps:
    - ${{ parameters.myStep }}