# File: azure-pipelines.yml

jobs:
- template: npm-with-params.yml  # Template reference
  parameters:
    name: Linux
    vmImage: 'ubuntu-latest'
    displayName: 'This is from main.yam'

- template: npm-with-params.yml  # Template reference
  parameters:
    name: macOS
    vmImage: 'macOS-latest'

- template: npm-with-params.yml  # Template reference
  parameters:
    name: Windows
    vmImage: 'windows-latest'