# File: templates/jobs.yml
jobs:
- job: 
  pool:
    name: production
    demands: agent.os -equals Linux
  steps:
  - bash: echo "Hello Ubuntu"

- job:
  pool:
    name: production
    demands: agent.os -equals Linux
  steps:
  - bash: echo "Hello Windows"