trigger: none

pool: 
  vmImage: 'ubuntu-latest'

parameters:
- name: Operating_Syatems
  type: string
  default: ubuntu
  values:
  - ubuntu
  - Redhat
  - CentOS
  - Windows

- name: Environments
  type: string
  default: Dev
  values:
  - Dev
  - UAT
  - Testing
  - Prod

variables: 
- name: myENV
  value: ${{ parameters.Environments}}

steps:
- ${{ if eq(variables.myENV, UAT) }}:
    - script: echo "UAT.yml"

- ${{ if eq(variables.myENV, Prod) }}:
    - script: echo "Prod.yml"
